### ISSUE TITLE
Footer alterations

### ISSUE THREAD

**Issue by arouault** [MAPC/leap-dashboard#15]
- [x] Please remove the creative commons logo
- [x] Make footer persistent across the site 
- [x] Add as text near the MAPC logo: 
> This dashboard was designed and built by the MAPC's Digital Services Group and the Clean Energy Department. 
- [x] Add links to reach "Learn More" and "Methodology" in the footer 
- [x] "Plug In to MAPC's Clean Energy programs"

**Comment by ericyoungberg** [comment]
Closed by b0a540a91bf0a26db8f9289f18afdb44cf08010c

**Comment by ericyoungberg** [comment]
Closed by b0a540a91bf0a26db8f9289f18afdb44cf08010c
